version: '3'
services:
  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB}
    restart: unless-stopped
    ports:
      - "${IP}:80:80"
      - "${IP}:443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - web_media:${NGINX_FILES_PATH}/site_media/
      - web_static:${NGINX_FILES_PATH}/static/
      - logs:${NGINX_FILES_PATH}/logs/

  nginx-gen:
    build: ./nginx-gen/
    command: -notify-sighup ${NGINX_WEB} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN}
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT}
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB}
      # ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory
      ACME_TOS_HASH: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b

  web:
    restart: always
    build: ./web/
    expose:
      - "8000"
    ports:
      - "8000:8000"
    container_name: ${APPNAME}

    volumes:
      - web_media:${NGINX_FILES_PATH}/site_media/
      - web_static:${NGINX_FILES_PATH}/static/
      - logs:${NGINX_FILES_PATH}/logs/

    env_file: ./.env
    environment:
      VIRTUAL_HOST: ${APPHOST}
      LETSENCRYPT_HOST: ${APPHOST}
      LETSENCRYPT_EMAIL: ${EMAIL}
    command: ./shell-script.sh
    networks: 
      default: {}

  postgres:
    restart: always
    image: postgres
    container_name: ${POSTGRES}

    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASS}  
    ports:
      - "${IP}:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks: 
      default: {}
      
    
volumes:
    web_media: {}
    web_static: {}
    logs: {}
    pgdata: {}

networks:
  default:
    external:
      name: ${NETWORK}